### ISSUE TITLE
Compilation errors in Go 1.2

### ISSUE THREAD

**Issue by tomp** [sbinet/igo#3]
When I try to compile the current version of igo/main.go in Go 1.2, it fails with these errors,

```
% go run main.go
# code.google.com/p/go.tools/go/types
../src/code.google.com/p/go.tools/go/types/exprstring.go:80: x.Slice3 undefined (type *ast.SliceExpr has no field or method Slice3)
../src/code.google.com/p/go.tools/go/types/exprstring.go:82: x.Max undefined (type *ast.SliceExpr has no field or method Max)
../src/code.google.com/p/go.tools/go/types/exprstring.go:83: x.Max undefined (type *ast.SliceExpr has no field or method Max)
```

I'm a Go newbie, so I don't know whether this indicates a problem with my build environment (though I doubt that) or with the main.go code, or how to fix it, if it's the later.

**Comment by sbinet** [comment]
hi Tom,

it seems you have remnants of a previous go-1.1 (or older) installation. `ast.SliceExpr.Slice3` was introduced in go-1.2.

what is the output of:

``` sh
$ go version
$ go env
```

?

-s

**Comment by tomp** [comment]
You're right, I still had a Go 1.1.2 installation on the machine where I tried this.  Igo builds in Go 1.2 just fine.  Thanks for the quick response and sorry for the false alarm.

**Comment by sbinet** [comment]
good.
